version: "3"

services:
 mysql-departamento-1:
  image: mysql:5.6
  environment:
    MYSQL_ROOT_PASSWORD: root-password
  ports:
    - 3307:3306
  volumes:
    - ./scripts/sql/Departamentos/:/docker-entrypoint-initdb.d/

 mysql-central:
  image: mysql:5.6
  environment:
    MYSQL_ROOT_PASSWORD: root-password
  ports:
    - 3308:3306
  volumes:
    - ./scripts/sql/Central/:/docker-entrypoint-initdb.d/
