version: "3"

services:

 mysql-central:
  image: mysql:5.6
  environment:
    MYSQL_ROOT_PASSWORD: root-password
  ports:
    - 3308:3306
  volumes:
    - ./scripts/sql/Central/:/docker-entrypoint-initdb.d/

 dpto-tacuarembo:
  build: ./API-Servidor-Departamento/
  ports:
    - "8001:80"
  depends_on:
    - "mysql-dpto-tacuarembo"
  links:
    - "mysql-dpto-tacuarembo:database"

 mysql-dpto-tacuarembo:
  image: mysql:5.6
  environment:
    MYSQL_ROOT_PASSWORD: root-password
  ports:
    - 4001:3306
  volumes:
    - ./scripts/sql/Departamentos/:/docker-entrypoint-initdb.d/

 dpto-montevideo:
  build: ./API-Servidor-Departamento/
  ports:
    - "8002:80"
  depends_on:
    - "mysql-dpto-montevideo"
  links:
    - "mysql-dpto-montevideo:database"

 mysql-dpto-montevideo:
  image: mysql:5.6
  environment:
    MYSQL_ROOT_PASSWORD: root-password
  ports:
    - 4002:3306
  volumes:
    - ./scripts/sql/Departamentos/:/docker-entrypoint-initdb.d/
