version: "3"

services:
 mysql-departamentos:
  image: mysql:5.6
  environment:
    MYSQL_ROOT_PASSWORD: root-password
  ports:
    - 3307:3306
  volumes:
    - ./scripts/sql/Departamentos/:/docker-entrypoint-initdb.d/
